Models/Application.cs
using System.ComponentModel.DataAnnotations;

namespace EmployeManagement.Models;

public class Application
{
   [Key]
   public int Id { get; set; }
   
   [Required]
   public string Name { get; set;}

    [Required]
   public string Subject { get; set; }

    [Required]
    public string Date{ get; set;}

    [Required]

    public string Status { get; set; }

    [Required]
    public string Description { get; set; }

}

Controllers/WorkerController.cs
using EmployeManagement.Data;
using EmployeManagement.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeManagement.Controllers;
public class WorkerController : Controller
{
    // get the data from the database 
    private readonly ApplicationDbContext _db;
    public WorkerController(ApplicationDbContext db)
    {
        _db = db;
    }
     public IActionResult index(int? id)
    {
        var employeesFromDb = _db.employees.Find(id);
        return View("~/Views/Worker/profile.cshtml", employeesFromDb);
    }
    [HttpPost]
    public IActionResult profile(login obj)
    {
        if (ModelState.IsValid)
        {
            if (obj.Id == null || obj.Id == 0)
            {
                return NotFound();
            }
            var employeesFromDb = _db.employees.Find(obj.Id);
            if (employeesFromDb == null)
            {   
                ViewData["ID"] = "ID is not found";
                return View("~/Views/Home/formWorker.cshtml");
            }
           if(employeesFromDb != null && obj.Password == employeesFromDb.Password){
                return View(employeesFromDb);
           }
           else{
                ViewData["Pass"] = "password not Match";
                return View("~/Views/Home/formWorker.cshtml");
           }
        }
        return View();
    }
    public IActionResult Application(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var employeesFromDb = _db.employees.Find(id);
        if (employeesFromDb == null)
        {
            return View();
        }
        ViewData["ID"] = id;
        ViewData["Name"] = employeesFromDb.Name;
        return View();
    }
    [HttpPost]
    public IActionResult Application(Application obj)
    {
        if (ModelState.IsValid)
        {
           _db.applications.Add(obj);
           _db.SaveChanges();
            var employeesFromDb = _db.employees.Find(obj.Id);
            return View("~/Views/Worker/profile.cshtml", employeesFromDb);
        }
        return View("~/Views/Worker/profile.cshtml");
    }
    public IActionResult Task(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var employeesFromDb = _db.task.Find(id);
        if (employeesFromDb == null)
        {
            ViewData["ID"] = id;
            return View("~/Views/Worker/taskNot.cshtml");
        }
        return View(employeesFromDb);
    }
    public IActionResult showDetails(int? id)
    {
         var employeesFromDb = _db.task.Find(id);
         return View(employeesFromDb);
    }
}

Views/Worker/Application.cshtml
@model Application

<!DOCTYPE html>
<html lang="en">

<head>

    <title>Automatic Popup</title>
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!--Stylesheets-->
    <style media="screen">
        body {

            background: url(https://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2015/10/interview-1200x641.jpg) no-repeat;
            background-size: cover;
        }

        *,
        :before,
        *:after {
            * padding: 0;
            margin: 0;
            box-sizing: border-box;
        }


        .popup {
            background-color: whitesmoke;
            width: 420px;
            padding: 30px 40px;
            position: absolute;
            transform: translate(-50%, -50%);
            left: 50%;
            top: 50%;
            border-radius: 8px;
            font-family: "Poppins", sans-serif;
            display: none;
            text-align: center;
        }

        .button1 {
            display: block;
            margin: 0 0 20px auto;
            background-color: transparent;
            font-size: 30px;
            color: #ffffff;
            background: green;
            border-radius: 100%;
            width: 40px;
            height: 40px;
            border: none;
            outline: none;
            cursor: pointer;
        }

        .popup h2 {
            margin-top: 2px;
        }

        .popup p {
            font-size: 14px;
            text-align: justify;
            margin: 24px 0;
            line-height: 18px;
        }

        .a {
            display: block;
            width: 89px;
            position: relative;
            margin: 10px auto;
            text-align: center;
            background-color: #0f72e5;
            border-radius: 20px;
            color: #ffffff;
            text-decoration: none;
            padding: 8px 0;
            float: left;
        }

        #Back {
            background: #0f72e5;
            border: none;
            color: white;
        }

        .btn_last {
            margin-top: 27px;
            background: #0f72e5;
            width: 88px;
            font-size: 13px;
            padding: 6px;
            border-radius: 14px;
            color: white;
            border: 1px solid green;
        }
    </style>

    <link rel="stylesheet" href="~/css/home.css">
    <link rel="stylesheet" href="~/css/admin.css">

</head>

<body>

   
    <div class="popup">
        <a class="a" asp-controller="Worker" asp-action="Index" asp-route-id="@ViewData["ID"]"> <button id="Back">Back</button>
        </a>
        <a asp-controller="Worker" asp-action="Index" asp-route-id="@ViewData["ID"]"> <button class="button1" id="close">&times;</button> </a>

        <h2 style="color : green;">Application Box</h2>

        <form action="" method="post">
            <p class="fromP">ID: <input asp-for="Id" type="text" name="" id="" class="inputID"
                    placeholder=@ViewData["ID"]> </p>
            <span asp-validation-for="Id" class="text-danger"></span>

            <p class="fromDate">Name: <input asp-for="Name" type="text" class="inputDate"
                    placeholder=@ViewData["Name"] /></p>
            <span asp-validation-for="Name" class="text-danger"></span>

            <p class="fromDate">Subject: <input asp-for="Subject" type="text" class="inputDate" /></p>
            <span asp-validation-for="Subject" class="text-danger"></span>

            <p class="fromDate">Date: <input asp-for="Date" type="date" class="inputDate" /></p>
            <span asp-validation-for="Date" class="text-danger"></span>


            <p class="fromDate">Status <input asp-for="Status" type="text" class="inputDate" placeholder="Request"></p>
            <span asp-validation-for="Status" class="text-danger"></span>

            <p class="fromDec" style="margin-top:10px">Description: </p>
            <input asp-for="Description" type="text" class="inputText" placeholder="Write down your words" />
            <span asp-validation-for="Description" class="text-danger"></span>

            <button class="btn_last" type="submit">Submit</button>

        </form>

    </div>


    <script type="text/javascript">
        window.addEventListener("load", function () {
            setTimeout(
                function open(event) {
                    document.querySelector(".popup").style.display = "block";
                },
                2000
            )
        });


        document.querySelector("#close").addEventListener("click", function () {
            document.querySelector(".popup").style.display = "none";
        });
    </script>
</body>

</html>

Views/Worker/Task.cshtml
@model TaskE

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Assigned Task</title>
  <style>
    body {

      background: url(https://bbdniit.ac.in/wp-content/uploads/2020/09/banner-background-without-image-min.jpg) no-repeat;
      background-size: auto;
    }

    .tasktable {
      height: 60vh;
      width: 100%;
      margin-left: 318px;

    }

    .topbar {
      background-color: rgb(19, 76, 122);
      overflow: hidden;
    }

    .topbar a {
      float: right;
      color: whitesmoke;
      text-align: centre;
      padding: 20px 26px;
      text-decoration: none;
      font-size: 23px;
    }


    }

    .apptable-title p {
      padding-top: 20px;
      padding-left: 50px;
    }

    .apptable {
      margin-top: 25px;
      margin-left: 50px;
      width: 100%;
    }

    th,
    td {
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: rgb(19, 76, 122);
      ;
      color: #fff;
      padding: 10px;
    }

    .row1 {
      background-color: #f5f6fa;
      color: black;
    }

    .fas {
      color: #0097e6;
    }

    tr:hover {
      background-color: #ffeaa7;
    }

    tr #emplename {
      color: #0097e6;
    }

    td span {
      padding: 4px;
    }

    #pending {
      background-color: #EA2027;
      border-radius: 10px;
      border: 1px solid #EA2027;
    }

    #done {
      border-radius: 10px;
      background-color: #10ac84;
      border: 1px solid #10ac84;
    }

    #ongoing {
      border-radius: 10px;
      background-color: #feca57;
      border: 1px solid #feca57;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="main">
      <div class="topbar">
        <a asp-controller="Home" asp-action="Index">Logout</a>
        <a asp-controller="Worker" asp-action="Index" asp-route-id="@Model.Id">Home</a>
        <a asp-controller="Worker" asp-action="Task" asp-route-id="@Model.Id">Assigned Task</a>
        <a asp-controller="Worker" asp-action="Application" asp-route-id="@Model.Id">Application</a>
      </div>

      <div class="topbar">
        <div class="title">
          <h2 style="color :white;  text-align: center;">Task Management</h2>
        </div>
      </div>
      <div class="tasktable">
        <div class="table-title">
        </div>
        <div class="apptable">
          <table>
            <tr>
              <th>Task No</th>
              <th>Task details</th>
              <th>Assign date</th>
              @* <th>Due Date</th> *@
              <th>Task Status</th>

            </tr>

            <tr class="row1">
              <td>@Model.Id</td>
              <td><a asp-controller="Worker" asp-action="showDetails" asp-route-id="@Model.Id">View more</a></td>
              <td>@Model.Date</td>
              @* <td>20/03/2022 </td> *@
              <td><button id="ongoing">@Model.Status</button> </td>



            </tr>



          </table>
        </div>

      </div>
    </div>
</body>

Views/Worker/profile.cshtml
@model Employe

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    
    <title>Employee's profile</title>
    <style>
        body{
            @* margin-top: 20px; *@
            background-color: paleturquoise;
        }
        .main{
            @* padding: 15px; *@
            font-family: Poppins;
        }
        .topbar{
            background-color:rgb(19, 76, 122);
            overflow:hidden;
        }
        .topbar a{
            float: right;
            color: whitesmoke;
            text-align: centre;
            padding: 20px 26px;
            text-decoration: none;
            font-size: 23px;
        }
        .sidebar{
            background-color: skyblue;
            color: white;
            height: 50%;
        }
        .sidebar a{
            margin-left: 10px;
            display:block;
            color: white;
            padding-bottom: 10px;
            font-size: 30px;
            text-decoration: none;
        }
        .card{
            position: relative;
            display: flex;
            flex-direction: column;
            
        }
        
        .content{
            background-color: whitesmoke;
        }
    </style>
    </head>
    <body>
        <div class="container">
            <div class="main">
                <div class="topbar">
                    <a asp-controller="Home" asp-action="Index" >Logout</a>
                    <a asp-controller="Worker" asp-action="Index" asp-route-id="@Model.Id">Home</a>
                    <a asp-controller="Worker" asp-action="Task" asp-route-id="@Model.Id">Assigned Task</a>
                    <a asp-controller="Worker" asp-action="Application" asp-route-id="@Model.Id" >Application</a>
                    </div>
                    <div class="row">
                        <div class="col-md-4 mt-1">
                            <div class="card text-centre sidebar">
                                <div class="card-body">
                                    <img src="https://static.vecteezy.com/system/resources/previews/002/318/271/original/user-profile-icon-free-vector.jpg" class="rounded-circle" width="100">
                                    <div class="mt-3">
                                        <h2> @Model.Name </h2>
                                        

                                    </div>
                            </div>  

                    </div>

        </div>
        <div class="col-md-8 mt-1">
            <div class="Card mb-3 content">
                <h1 class="m-3 pt-3">About</h1>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Full Name</h5>
                        </div>
                        <div class="col-md-9 text-secondary">
                           @Model.Name
                        </div> 

                </div>
                <hr>
                <div class="row">
                    <div class="col-md-3">
                        <h5>Email</h5>
                    </div> 
                    <div class="col-md-9 text-secondary">
                        @Model.Email
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-3">
                        <h5>Phone</h5>
                        </div>
                   
                    <div class="col-md-9 text-secondary">
                       @Model.Phone
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-3">
                        <h5>Salary</h5>
                        
                    </div> 
                    <div class="col-md-9 text-secondary">
                       @Model.Salary
                        </div>
                    </div>
                    <hr>
                </div>
             </div>
             
                      </div>
                      </div>
                 </div>
             </div>
        </div>
                 </div>
             </div>
             
             </div>
    </body>

Views/Worker/showDetails.cshtml
@model TaskE

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>Employee's profile</title>
    <style>
        body {
            @*margin-top:20px;*@background-color: paleturquoise;
        }

        .main {
            @*padding:15px;*@font-family: Poppins;
        }

        .topbar {
            background-color: rgb(19, 76, 122);
            overflow: hidden;
        }

        .topbar a {
            float: right;
            color: whitesmoke;
            text-align: centre;
            padding: 20px 26px;
            text-decoration: none;
            font-size: 23px;
        }

        .sidebar {
            background-color: skyblue;
            color: white;
            height: 50%;
        }

        .sidebar a {
            margin-left: 10px;
            display: block;
            color: white;
            padding-bottom: 10px;
            font-size: 30px;
            text-decoration: none;
        }

        .card {
            position: relative;
            display: flex;
            flex-direction: column;

        }

        .content {
            background-color: whitesmoke;
        }
    </style>

    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/home.css">
</head>

<body>
    <div class="container">
        <div class="main">
            <div class="topbar">
                <a asp-controller="Home" asp-action="Index">Logout</a>
                <a asp-controller="Worker" asp-action="Index" asp-route-id="@Model.Id">Home</a>
                <a asp-controller="Worker" asp-action="Task" asp-route-id="@Model.Id">Assigned Task</a>
                <a asp-controller="Worker" asp-action="Application" asp-route-id="@Model.Id">Application</a>
            </div>

            <div class="loginForm">
                <p class="loginHeading">Task for ID @Model.Id</p>
                <p>Name: @Model.Name</p>
                <p>@Model.Details</p>

            </div>

        </div>
    </div>
</body>

Views/Worker/taskNot.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Assigned Task</title>
  <style>
    body {

      background: url(https://bbdniit.ac.in/wp-content/uploads/2020/09/banner-background-without-image-min.jpg) no-repeat;
      background-size: auto;
    }

    .tasktable {
      height: 60vh;
      width: 100%;
      margin-left: 318px;

    }

    .topbar {
      background-color: rgb(19, 76, 122);
      overflow: hidden;
    }

    .topbar a {
      float: right;
      color: whitesmoke;
      text-align: centre;
      padding: 20px 26px;
      text-decoration: none;
      font-size: 26px;
    }


    }

    .apptable-title p {
      padding-top: 20px;
      padding-left: 50px;
    }

    .apptable {
      margin-top: 25px;
      margin-left: 50px;
      width: 100%;
    }

    th,
    td {
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: rgb(19, 76, 122);
      ;
      color: #fff;
      padding: 10px;
    }

    .row1 {
      background-color: #f5f6fa;
      color: black;
    }

    .fas {
      color: #0097e6;
    }

    tr:hover {
      background-color: #ffeaa7;
    }

    tr #emplename {
      color: #0097e6;
    }

    td span {
      padding: 4px;
    }

    #pending {
      background-color: #EA2027;
      border-radius: 10px;
      border: 1px solid #EA2027;
    }

    #done {
      border-radius: 10px;
      background-color: #10ac84;
      border: 1px solid #10ac84;
    }

    #ongoing {
      border-radius: 10px;
      background-color: #feca57;
      border: 1px solid #feca57;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="main">
      <div class="topbar">
        <a asp-controller="Home" asp-action="Index">Logout</a>
        <a asp-controller="Worker" asp-action="Index" asp-route-id="@ViewData["ID"]">Home</a>
        <a asp-controller="Worker" asp-action="Task" asp-route-id="@ViewData["ID"]">Assigned Task</a>
        <a asp-controller="Worker" asp-action="Application" asp-route-id="@ViewData["ID"]">Application</a>
      </div>

      <div class="topbar">
        <div class="title">
          <h2 style="color :white;  text-align: center;">Task Management</h2>
        </div>
      </div>
      <div class="tasktable">
        <div class="table-title">
        </div>
        <div class="apptable">
          <table>
            <tr>
              <th>Task No</th>
              <th>Task details</th>
              <th>Assign date</th>
              @* <th>Due Date</th> *@
              <th>Task Status</th>

            </tr>

            <p>No Task Available</p>



            </tr>



          </table>
        </div>

      </div>
    </div>
</body>